clonedrive:
  path: C:\Program Files\Elaborate Bytes\VirtualCloneDrive\Daemon.exe
  letter: K
  index: 0
decrypter: C:\Program Files\DVD Decrypter\DVDDecrypter.exe
mkvmerge: C:\Program Files\MKVtoolnix\mkvmerge.exe
megui: C:\Program Files\megui
