clonedrive:
  path: C:\Program Files (x86)\Elaborate Bytes\VirtualCloneDrive\Daemon.exe
  letter: H
  index: 0
decrypter: C:\Program Files (x86)\DVD Decrypter\DVDDecrypter.exe
megui: C:\Program Files (x86)\megui
